# UNDER CONSTRUCTION

Point point             # 2D coordinates of the corner

int32 orientation       # orientation angle from the line1 to x axis, in [-pi,pi]
int32 aperture          # angle aperture of the corner in [0,2pi]. Aperture angle defined passing thorugh the shadow area of the scan (not crossing rays)

Line line1              # line1 of the corner
Line line2              # line2 of the corner
