Header header            # timestamp in the header is the acquisition time of
                         # the first ray in the scan.
                         #
                         # in frame frame_id, angles are measured around
                         # the positive Z axis (counterclockwise, if Z is up)
                         # with zero angle being forward along the x axis

uint8 sensorId    # id of sensor


uint8 ModeBtn
uint8 HwModeBtn
uint8 SetMinBtn
uint8 ResPlusBtn
uint8 CancelBtn
uint8 OnOffBtn
uint8 EmergencyBtn
