Header header

uint8 sensorId    # id of sensor

float32 vx              # vehicle speed
float32 ax              # acceleration longitudinal direction
float32 ay              # acceleration lateral direction (postive number means acceleration to the left )
float32 psid            # yaw rate (positive rotation means steering left)
float32 delta           # steering angle (positive number means steering left)
