#/gazebo_ros_control_params.yaml
gazebo_ros_control/pid_gains: 
 yumi_joint_1_r: 
	p: 1.41
 yumi_joint_2_r: 
	p: -2.1
 yumi_joint_3_r: 
	p: 0.30
 yumi_joint_4_r: 
	p: 0.00
 yumi_joint_5_r: 
	p: 0.00
 yumi_joint_6_r: 
	p: 0.00
 yumi_joint_7_r: 
	p: -0.71
 yumi_joint_1_l: 
	p: -1.41
 yumi_joint_2_l: 
	p: -2.1
 yumi_joint_3_l: 
	p: 0.30
 yumi_joint_4_l: 
	p: 0.00
 yumi_joint_5_l: 
	p: 0.00
 yumi_joint_6_l: 
	p: 0.00
 yumi_joint_7_l: 
	p: 0.71


  
