# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

# Joint Trajectory Position Controlles ----------------------------------------
joint_traj_pos_controller_l:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l

joint_traj_pos_controller_r:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r

# Joint Trajectory Velocity Controller ----------------------------------------
joint_traj_vel_controller_l:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l
  gains:
    yumi_joint_1_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_2_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_7_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_3_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_4_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_5_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_6_l: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
  constraints:
    goal_time: 1
  stop_trajectory_duration: 0
  velocity_ff:
    yumi_joint_1_l: 1.0
    yumi_joint_2_l: 1.0
    yumi_joint_3_l: 1.0
    yumi_joint_4_l: 1.0
    yumi_joint_5_l: 1.0
    yumi_joint_6_l: 1.0
    yumi_joint_7_l: 1.0



joint_traj_vel_controller_r:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r
  gains:
    yumi_joint_1_r: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_2_r: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_7_r: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_3_r: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_4_r: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_5_r: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_joint_6_r: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
  constraints:
    goal_time: 1
  velocity_ff:
    yumi_joint_1_r: 1.0
    yumi_joint_2_r: 1.0
    yumi_joint_3_r: 1.0
    yumi_joint_4_r: 1.0
    yumi_joint_5_r: 1.0
    yumi_joint_6_r: 1.0
    yumi_joint_7_r: 1.0
  stop_trajectory_duration: 0
