SCANNER_TO_CENTER_POS: 0.41
PLATFORM_LENGTH_CENTER_TO_EDGE: 0.5
BACKING_DISTANCE: 1.0

ACCEPTED_X_ERROR: 0.01
ACCEPTED_Y_ERROR: 0.01
ACCEPTED_THETA_ERROR: 0.035

MAX_LINER_SPEED: 0.2
MIN_LINER_SPEED: 0.01
MAX_ANGULAR_SPEED: 0.6
MIN_ANGULAR_SPEED: 0.02

TIME_DURATION: 0.1

X_KP: 0.2
X_KD: 0.1
X_KI: 0.01

Y_KP: 1.0
Y_KD: 0.3
Y_KI: 0.01

THETA_KP: 0.5
THETA_KD: 0.1
THETA_KI: 0.01

